# Generated by Django 3.1.1 on 2020-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_role',
            field=models.CharField(choices=[('DIR', 'Director'), ('PDR', 'Producer')], default='DIR', max_length=3),
        ),
    ]
