# Generated by Django 3.1.1 on 2020-10-01 04:04

from django.db import migrations, models
import universe.enums


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_auto_20200930_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_role',
            field=models.CharField(choices=[('DIR', 'Director'), ('PDR', 'Producer')], default=universe.enums.JobRoleType, max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', to='universe.Movie'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='movies',
            field=models.ManyToManyField(related_name='planets', to='universe.Movie'),
        ),
    ]
